name: chron39
channels:
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - astropy
  - matplotlib=3.8
  - numba
  - numpy
  - pathlib
  - pip
  - pytest
  - python=3.9
  - pyyaml
  - scikit-learn=1.1
  - scipy
  - threadpoolctl
prefix: /Users/tcrundall/opt/anaconda3/envs/chron39
